### ISSUE TITLE
This is not a Issue

### ISSUE THREAD

**Issue by IosifSilaghi** [ArielTEP/android-traffic-simulator#1]
Ariel, please check your Email, I need your help.

**Comment by ArielTEP** [comment]
Hi,

Sure. What’s going on?

—
Ariel

On 8 May 2020, at 10:53, IosifSilaghi <notifications@github.com> wrote:

﻿

Ariel, please check your Email, I need your help.

**Comment by IosifSilaghi** [comment]
Greetings Ariel,

I wrote you with my other email, heres the text.

Sincerely,
Iosif

Ariel T. Espindola <notifications@github.com> schrieb am Fr., 8. Mai 2020,
19:56:

> Hi,
>
> Sure. What’s going on?
>
> —
> Ariel
>

**Comment by ArielTEP** [comment]
What do you need help about?

**Comment by IosifSilaghi** [comment]
This is the error I am facing.
Warning: The initial conditions of the analysis are not set to
"User-defined", but to C1 (in C1). The circuit may be simulated differently
than intended.

I also send you my circuit

Ariel T. Espindola <notifications@github.com> schrieb am Fr., 8. Mai 2020,
20:06:

**Comment by IosifSilaghi** [comment]
Mate?

Am Fr., 8. Mai 2020 um 21:08 Uhr schrieb Only Urbexpost <
onlyurbexpost01@gmail.com>:
